#!/usr/bin/env python3
from zipfile import ZipFile
import json

from beat_saber_map_utils.load import Info

info = Info()


def zip_filename(filename):
    return "{}/{}".format(info.map_title, filename)


with ZipFile(info.revision_description + ".zip", mode="x") as output_zip:
    # Add files within a directory named for the map to prevent a mess if
    # extracted into the working directory.
    def zip_add(filename):
        output_zip.write(filename, zip_filename(filename))

    # Add a JSON file, compacting it first.
    def zip_add_json(filename):
        contents = json.load(open(filename))
        output_zip.writestr(zip_filename(filename),
                            json.dumps(contents, separators=(',', ':')))

    zip_add_json(info.filename)
    zip_add(info["coverImagePath"])

    # Multiple difficulties may share an audio file; add each once to avoid
    # zipfile printing "UserWarning: Duplicate name" during normal operation.
    audio_paths = set()
    for level in info["difficultyLevels"]:
        audio_paths.add(level["audioPath"])
        zip_add_json(level["jsonPath"])

    for audio_path in audio_paths:
        zip_add(audio_path)
