#!/usr/bin/env python3
from zipfile import ZipFile

from beat_saber_map_utils.load import Info

info = Info()

with ZipFile(info.revision_description + ".zip", mode="x") as output_zip:
    # Add files within a directory named for the song to prevent a mess if
    # extracted into the working directory.
    def zip_add(filename):
        output_zip.write(filename, "{}/{}".format(info.song_title, filename))

    zip_add(info.filename)
    zip_add(info["coverImagePath"])

    # Multiple difficulties may share an audio file; add each once to avoid
    # zipfile printing "UserWarning: Duplicate name" during normal operation.
    audio_paths = set()
    for level in info["difficultyLevels"]:
        audio_paths.add(level["audioPath"])
        zip_add(level["jsonPath"])

    for audio_path in audio_paths:
        zip_add(audio_path)
