#!/usr/bin/env python3
import argparse
import json

parser = argparse.ArgumentParser()
parser.add_argument('path')
args = parser.parse_args()

# TODO: This m ight be a good script to use in a pre-commit/pre-add hook to format json.

with open(args.path) as input_file:
    pretty_printed = json.dumps(json.load(input_file), indent=4, sort_keys=True)

with open(args.path, 'w') as output_file:
    output_file.writelines(pretty_printed)
