#!/usr/bin/env python3
import argparse
import json

from beat_saber_map_utils.load import Info

parser = argparse.ArgumentParser()
parser.add_argument('paths', nargs="*")
args = parser.parse_args()

# TODO: This m ight be a good script to use in a pre-commit/pre-add hook to format json.

if not args.paths:
    info = Info()

    args.paths.append(info.filename)
    for level in info["difficultyLevels"]:
        args.paths.append(level["jsonPath"])

for path in args.paths:
    with open(path) as input_file:
        pretty_printed = json.dumps(json.load(input_file), indent=4, sort_keys=True)

    with open(path, 'w') as output_file:
        output_file.writelines(pretty_printed)
